services:
  db:
    image: postgres:17
    container_name: stride-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: stride_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  rails:
    build: .
    container_name: stride-rails
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgres://postgres:secret@db:5432/stride_development
    stdin_open: true
    tty: true

volumes:
  pgdata: