name: Build + Deploy to ECS

on:
  push:
    branches: [main]

env:
  AWS_REGION: us-west-2

jobs:
  deploy:
    name: Build + Push + Update ECS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ env.IMAGE_URI }} \
            --push .

        env:
          IMAGE_URI: 315183407242.dkr.ecr.us-west-2.amazonaws.com/stride-server:latest
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Update ECS service (Force new deployment)
        run: |
          aws ecs update-service \
            --cluster stride-cluster \
            --service stride-service \
            --force-new-deployment \
            --region us-west-2

        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
