name: Infrastructure Provisioning (Terraform)

on:
  push:
    paths:
      - 'infra/**'
      - '.github/workflows/infra.yml'
    branches: [main]
  workflow_dispatch: # manual run button

jobs:
  terraform:
    name: Terraform Plan + Apply
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init -backend-config=prod/backend-config.hcl

      - name: Terraform Plan
        run: terraform plan -var-file=prod/terraform.tfvars

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file=prod/terraform.tfvars
